@extends('layouts.app')
@section('title','Monitoring Nilai - '.config('app.name'))
@section('page_title','Monitoring Nilai')
@section('content')
<div class="space-y-6">
    <section class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100">
        <h2 class="text-xl font-black text-slate-950">Monitoring Nilai KP</h2>
        <form class="mt-5 grid gap-3 md:grid-cols-4"><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Cari nama/NIM" class="rounded-2xl border-slate-200 text-sm"><select name="period" class="rounded-2xl border-slate-200 text-sm"><option value="">Semua periode</option>@foreach($periods as $period)<option value="{{ $period->id }}" @selected(($filters['period'] ?? '') == $period->id)>{{ $period->name }}</option>@endforeach</select><button class="rounded-2xl border border-cyan-200 px-4 py-2 text-sm font-bold text-cyan-700">Filter</button></form>
    </section>
    <section class="overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-100"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100 text-sm"><thead class="bg-slate-50 text-left text-xs font-black uppercase tracking-widest text-slate-500"><tr><th class="px-5 py-3">Mahasiswa</th><th class="px-5 py-3">Tempat</th><th class="px-5 py-3">Kelengkapan</th><th class="px-5 py-3">Nilai Akhir</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($assignments as $assignment)<tr><td class="px-5 py-4"><p class="font-bold">{{ $assignment->student->user->name }}</p><p class="text-xs text-slate-500">{{ $assignment->student->nim }}</p></td><td class="px-5 py-4">{{ $assignment->place->name }}</td><td class="px-5 py-4">{{ $assignment->scoresCompletionPercentage() }}%</td><td class="px-5 py-4">{{ $assignment->finalScore?->final_score ?? '-' }}</td><td class="px-5 py-4">@if($assignment->finalScore)<span class="rounded-full {{ $assignment->finalScore->statusBadgeClass() }} px-3 py-1 text-xs font-bold">{{ $assignment->finalScore->statusLabel() }}</span>@else<span class="text-slate-400">Belum dihitung</span>@endif</td><td class="px-5 py-4"><a class="font-bold text-cyan-700" href="{{ route('management.scores.show',$assignment) }}">Detail</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">Belum ada penempatan KP.</td></tr>@endforelse</tbody></table></div><div class="p-5">{{ $assignments->links() }}</div></section>
</div>
@endsection
