@extends('layouts.app')
@section('title','Detail Nilai - '.config('app.name'))
@section('page_title','Detail Nilai')
@section('content')
<div class="space-y-6">
    <section class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100"><div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 class="text-xl font-black text-slate-950">{{ $assignment->student->user->name }}</h2><p class="text-sm text-slate-500">{{ $assignment->student->nim }} · {{ $assignment->place->name }}</p></div><div class="text-right"><p class="text-3xl font-black text-cyan-700">{{ $assignment->finalScore?->final_score ?? '-' }}</p><p class="text-sm font-bold text-slate-500">Grade {{ $assignment->finalScore?->final_grade ?? '-' }}</p></div></div></section>
    <section class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100"><h3 class="font-black text-slate-950">Komponen Nilai</h3><div class="mt-4 space-y-3">@foreach($assignment->period->assessmentComponents->where('status','aktif') as $component)@php($score=$assignment->scores->firstWhere('kp_assessment_component_id',$component->id))<div class="rounded-2xl border border-slate-100 p-4"><div class="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><p class="font-bold">{{ $component->component_name }}</p><p class="text-xs text-slate-500">{{ $component->assessorTypeLabel() }} · Bobot {{ $component->weight }}%</p></div><div class="text-sm font-bold">{{ $score?->score ?? '-' }} / {{ $component->max_score }} · Weighted {{ $score?->weighted_score ?? '-' }} @if($score)<span class="ml-2 rounded-full {{ $score->statusBadgeClass() }} px-2 py-1 text-xs">{{ $score->statusLabel() }}</span>@endif</div></div></div>@endforeach</div></section>
    <section class="flex flex-wrap gap-2 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100">
        <form method="POST" action="{{ route('management.scores.calculate',$assignment) }}">@csrf<button class="rounded-2xl border border-cyan-200 px-4 py-2 text-sm font-bold text-cyan-700">Hitung Ulang</button></form>
        <form method="POST" action="{{ route('management.scores.finalize',$assignment) }}" onsubmit="return confirm('Finalisasi dan kunci nilai?')">@csrf<button class="rounded-2xl bg-cyan-700 px-4 py-2 text-sm font-bold text-white">Finalisasi</button></form>
        @if($assignment->finalScore)<form method="POST" action="{{ route('management.final-scores.publish',$assignment->finalScore) }}" onsubmit="return confirm('Publish nilai ke mahasiswa?')">@csrf<button class="rounded-2xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Publish</button></form><form method="POST" action="{{ route('management.final-scores.unlock',$assignment->finalScore) }}" onsubmit="return confirm('Buka kunci nilai?')">@csrf<input type="hidden" name="reason" value="Dibuka ulang oleh Koordinator/Admin"><button class="rounded-2xl border border-amber-200 px-4 py-2 text-sm font-bold text-amber-700">Unlock</button></form>@endif
    </section>
</div>
@endsection
