@extends('layouts.app')
@section('title','Pengajuan Sidang - '.config('app.name'))
@section('page_title','Pengajuan Sidang')
@section('content')
<div class="space-y-5">
<x-ui.card><form method="GET" class="grid gap-3 md:grid-cols-[1fr_220px_220px_auto]"><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Cari mahasiswa/NIM" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><select name="period" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua Periode</option>@foreach($periods as $period)<option value="{{ $period->id }}" @selected(($filters['period'] ?? '') == $period->id)>{{ $period->name }}</option>@endforeach</select><select name="status" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua Status</option>@foreach(['diajukan'=>'Diajukan','disetujui'=>'Disetujui','dijadwalkan'=>'Dijadwalkan','revisi'=>'Revisi','ditolak'=>'Ditolak'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filter</button></form></x-ui.card>
<section class="si-table-wrap"><div class="overflow-x-auto"><table><thead><tr><th>Mahasiswa</th><th>Periode</th><th>Tempat</th><th>Pembimbing</th><th>Status</th><th class="text-right">Aksi</th></tr></thead><tbody>@forelse($requests as $examRequest)<tr><td><div class="font-semibold">{{ $examRequest->assignment->student->user->name }}</div><div class="text-xs text-slate-500">{{ $examRequest->assignment->student->nim ?: '-' }}</div></td><td>{{ $examRequest->assignment->period->name }}</td><td>{{ $examRequest->assignment->place->name }}</td><td>{{ $examRequest->assignment->internalSupervisor?->user?->name ?? '-' }}</td><td><span class="rounded-full px-2 py-1 text-xs font-semibold ring-1 {{ $examRequest->statusBadgeClass() }}">{{ $examRequest->statusLabel() }}</span></td><td class="text-right"><a href="{{ route('management.exam-requests.show',$examRequest) }}" class="rounded-lg border border-cyan-200 px-3 py-1.5 text-xs font-semibold text-cyan-700">Detail</a></td></tr>@empty<tr><td colspan="6" class="py-10 text-center text-slate-500">Belum ada pengajuan sidang.</td></tr>@endforelse</tbody></table></div><div class="border-t px-4 py-3">{{ $requests->links() }}</div></section>
</div>
@endsection
