@extends('layouts.app')
@section('title','Log Aktivitas Logbook - '.config('app.name'))
@section('page_title','Log Aktivitas Logbook')
@section('content')
<div class="space-y-5">
<section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><form method="GET" class="grid gap-3 md:grid-cols-[220px_220px_auto]"><select name="period" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua Periode</option>@foreach($periods as $period)<option value="{{ $period->id }}" @selected(($filters['period'] ?? '') == $period->id)>{{ $period->name }}</option>@endforeach</select><input name="action" value="{{ $filters['action'] ?? '' }}" placeholder="Action" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filter</button></form></section>
<section class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-500"><tr><th class="px-4 py-3">Waktu</th><th class="px-4 py-3">User</th><th class="px-4 py-3">Mahasiswa</th><th class="px-4 py-3">Action</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Catatan</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($logs as $log)<tr><td class="px-4 py-4">{{ $log->created_at->format('d M Y H:i') }}</td><td class="px-4 py-4">{{ $log->user?->name ?? '-' }}</td><td class="px-4 py-4">{{ $log->logbook?->assignment?->student?->user?->name ?? '-' }}</td><td class="px-4 py-4">{{ str_replace('_',' ', $log->action) }}</td><td class="px-4 py-4">{{ $log->old_status ?: '-' }} -> {{ $log->new_status ?: '-' }}</td><td class="px-4 py-4">{{ $log->note ?: '-' }}</td></tr>@empty<tr><td colspan="6" class="px-4 py-10 text-center text-slate-500">Belum ada log aktivitas logbook.</td></tr>@endforelse</tbody></table></div><div class="border-t px-4 py-3">{{ $logs->links() }}</div></section>
</div>
@endsection
