@csrf
@if($place->exists) @method('PUT') @endif
<section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="grid gap-4 md:grid-cols-2">
<div><label class="text-sm font-semibold text-slate-700">Nama Tempat</label><input name="name" value="{{ old('name', $place->name) }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error('name')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
<div><label class="text-sm font-semibold text-slate-700">Tipe</label><select name="type" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@foreach(\App\Models\KpPlace::TYPES as $type)<option value="{{ $type }}" @selected(old('type', $place->type ?: 'apotek') === $type)>{{ str_replace('_', ' ', ucfirst($type)) }}</option>@endforeach</select></div>
<div><label class="text-sm font-semibold text-slate-700">Kota</label><input name="city" value="{{ old('city', $place->city) }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"></div>
<div><label class="text-sm font-semibold text-slate-700">Provinsi</label><input name="province" value="{{ old('province', $place->province) }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"></div>
<div><label class="text-sm font-semibold text-slate-700">Contact Person</label><input name="contact_person" value="{{ old('contact_person', $place->contact_person) }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"></div>
<div><label class="text-sm font-semibold text-slate-700">Telepon</label><input name="phone" value="{{ old('phone', $place->phone) }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"></div>
<div><label class="text-sm font-semibold text-slate-700">Email</label><input type="email" name="email" value="{{ old('email', $place->email) }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error('email')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
<div><label class="text-sm font-semibold text-slate-700">Status</label><select name="status" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="aktif" @selected(old('status', $place->status ?: 'aktif') === 'aktif')>Aktif</option><option value="nonaktif" @selected(old('status', $place->status) === 'nonaktif')>Nonaktif</option></select></div>
<div class="md:col-span-2"><label class="text-sm font-semibold text-slate-700">Alamat</label><textarea name="address" rows="3" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">{{ old('address', $place->address) }}</textarea></div>
<div class="md:col-span-2"><label class="text-sm font-semibold text-slate-700">Deskripsi</label><textarea name="description" rows="3" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">{{ old('description', $place->description) }}</textarea></div>
</div><div class="mt-6 flex justify-end gap-2"><a href="{{ route('management.kp-places.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Batal</a><button class="rounded-lg bg-teal-600 px-4 py-2 text-sm font-semibold text-white">Simpan Tempat</button></div></section>
