@extends('layouts.app')
@section('title', 'Tempat KP - '.config('app.name'))
@section('page_title', 'Tempat KP')
@section('content')
<div class="space-y-5">
@if($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<div class="flex flex-col gap-3 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 lg:flex-row lg:items-end lg:justify-between">
<form method="GET" class="grid flex-1 gap-3 md:grid-cols-[1fr_180px_180px_auto]"><div><label class="text-xs font-semibold uppercase tracking-wide text-slate-500">Cari</label><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Nama atau kota" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"></div><div><label class="text-xs font-semibold uppercase tracking-wide text-slate-500">Tipe</label><select name="type" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua</option>@foreach(\App\Models\KpPlace::TYPES as $type)<option value="{{ $type }}" @selected(($filters['type'] ?? '') === $type)>{{ str_replace('_', ' ', ucfirst($type)) }}</option>@endforeach</select></div><div><label class="text-xs font-semibold uppercase tracking-wide text-slate-500">Status</label><select name="status" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua</option><option value="aktif" @selected(($filters['status'] ?? '') === 'aktif')>Aktif</option><option value="nonaktif" @selected(($filters['status'] ?? '') === 'nonaktif')>Nonaktif</option></select></div><button class="self-end rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filter</button></form>
<a href="{{ route('management.kp-places.create') }}" class="rounded-lg bg-teal-600 px-4 py-2 text-center text-sm font-semibold text-white">Tambah Tempat</a></div>
<div class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Tempat</th><th class="px-4 py-3">Tipe</th><th class="px-4 py-3">Kota</th><th class="px-4 py-3">Kontak</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Kuota</th><th class="px-4 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($places as $place)<tr><td class="px-4 py-4"><div class="font-semibold text-slate-950">{{ $place->name }}</div><div class="text-xs text-slate-500">{{ $place->email ?: '-' }}</div></td><td class="px-4 py-4">{{ $place->typeLabel() }}</td><td class="px-4 py-4">{{ $place->city ?: '-' }}</td><td class="px-4 py-4">{{ $place->contact_person ?: '-' }}<br><span class="text-xs text-slate-500">{{ $place->phone ?: '-' }}</span></td><td class="px-4 py-4"><span class="rounded-full {{ $place->statusBadgeClass() }} px-2 py-1 text-xs font-semibold">{{ $place->statusLabel() }}</span></td><td class="px-4 py-4">{{ $place->quotas_count }}</td><td class="px-4 py-4 text-right"><a href="{{ route('management.kp-places.show', $place) }}" class="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-700">Detail</a> <a href="{{ route('management.kp-places.edit', $place) }}" class="rounded-lg border border-teal-200 px-3 py-1.5 text-xs font-semibold text-teal-700">Edit</a></td></tr>@empty<tr><td colspan="7" class="px-4 py-10 text-center text-slate-500">Belum ada tempat KP.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-200 px-4 py-3">{{ $places->links() }}</div></div>
</div>
@endsection
