@extends('layouts.app')
@section('title', 'Kuota Tempat KP - '.config('app.name'))
@section('page_title', 'Kuota Tempat KP')
@section('content')
<div class="space-y-5">
@if($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<div class="flex flex-col gap-3 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 lg:flex-row lg:items-end lg:justify-between"><form method="GET" class="grid flex-1 gap-3 md:grid-cols-[1fr_180px_160px_160px_auto]"><div><label class="text-xs font-semibold uppercase tracking-wide text-slate-500">Cari Tempat</label><input name="q" value="{{ $filters['q'] ?? '' }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"></div><div><label class="text-xs font-semibold uppercase tracking-wide text-slate-500">Periode</label><select name="period" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua</option>@foreach($periods as $period)<option value="{{ $period->id }}" @selected(($filters['period'] ?? '') == $period->id)>{{ $period->name }}</option>@endforeach</select></div><div><label class="text-xs font-semibold uppercase tracking-wide text-slate-500">Tipe</label><select name="type" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua</option>@foreach(\App\Models\KpPlace::TYPES as $type)<option value="{{ $type }}" @selected(($filters['type'] ?? '') === $type)>{{ str_replace('_', ' ', ucfirst($type)) }}</option>@endforeach</select></div><div><label class="text-xs font-semibold uppercase tracking-wide text-slate-500">Status</label><select name="status" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua</option><option value="open" @selected(($filters['status'] ?? '') === 'open')>Dibuka</option><option value="closed" @selected(($filters['status'] ?? '') === 'closed')>Ditutup</option></select></div><button class="self-end rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filter</button></form><a href="{{ route('management.kp-place-quotas.create') }}" class="rounded-lg bg-teal-600 px-4 py-2 text-center text-sm font-semibold text-white">Tambah Kuota</a></div>
<div class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Periode</th><th class="px-4 py-3">Tempat</th><th class="px-4 py-3">Kuota</th><th class="px-4 py-3">Terisi</th><th class="px-4 py-3">Sisa</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($quotas as $quota)<tr><td class="px-4 py-4">{{ $quota->period->name }}</td><td class="px-4 py-4"><div class="font-semibold">{{ $quota->place->name }}</div><div class="text-xs text-slate-500">{{ $quota->place->typeLabel() }}</div></td><td class="px-4 py-4 font-bold">{{ $quota->quota }}</td><td class="px-4 py-4">{{ $quota->filledCount() }}</td><td class="px-4 py-4">{{ $quota->remainingQuota() }}</td><td class="px-4 py-4"><span class="rounded-full {{ $quota->statusBadgeClass() }} px-2 py-1 text-xs font-semibold">{{ $quota->statusLabel() }}</span></td><td class="px-4 py-4 text-right"><a href="{{ route('management.kp-place-quotas.show', $quota) }}" class="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-700">Detail</a> <a href="{{ route('management.kp-place-quotas.edit', $quota) }}" class="rounded-lg border border-teal-200 px-3 py-1.5 text-xs font-semibold text-teal-700">Edit</a><form class="mt-2 inline-block" method="POST" action="{{ route('management.kp-place-quotas.toggle-open', $quota) }}" onsubmit="return confirm('Ubah status buka/tutup kuota ini?')">@csrf<button class="rounded-lg border border-amber-200 px-3 py-1.5 text-xs font-semibold text-amber-700">{{ $quota->is_open ? 'Tutup' : 'Buka' }}</button></form></td></tr>@empty<tr><td colspan="7" class="px-4 py-10 text-center text-slate-500">Belum ada kuota tempat KP.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-200 px-4 py-3">{{ $quotas->links() }}</div></div>
</div>
@endsection
