@extends('layouts.app')
@section('title', 'Persyaratan Dokumen - '.config('app.name'))
@section('page_title', 'Persyaratan Dokumen')
@section('content')
<div class="space-y-5">
@if($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<div class="flex flex-col gap-3 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 lg:flex-row lg:items-end lg:justify-between"><form method="GET" class="grid flex-1 gap-3 md:grid-cols-[1fr_1fr_auto]"><div><label class="text-xs font-semibold uppercase tracking-wide text-slate-500">Cari</label><input name="q" value="{{ $filters['q'] ?? '' }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"></div><div><label class="text-xs font-semibold uppercase tracking-wide text-slate-500">Periode</label><select name="period" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua</option>@foreach($periods as $period)<option value="{{ $period->id }}" @selected(($filters['period'] ?? '') == $period->id)>{{ $period->name }}</option>@endforeach</select></div><button class="self-end rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filter</button></form><a href="{{ route('management.document-requirements.create') }}" class="rounded-lg bg-teal-600 px-4 py-2 text-sm font-semibold text-white">Tambah Persyaratan</a></div>
<div class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Periode</th><th class="px-4 py-3">Dokumen</th><th class="px-4 py-3">Wajib</th><th class="px-4 py-3">Tipe</th><th class="px-4 py-3">Max</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($requirements as $requirement)<tr><td class="px-4 py-4">{{ $requirement->period->name }}</td><td class="px-4 py-4"><div class="font-semibold">{{ $requirement->name }}</div><div class="text-xs text-slate-500">{{ $requirement->description ?: '-' }}</div></td><td class="px-4 py-4">{{ $requirement->is_required ? 'Ya' : 'Tidak' }}</td><td class="px-4 py-4">{{ $requirement->allowed_file_types }}</td><td class="px-4 py-4">{{ $requirement->max_file_size_mb }} MB</td><td class="px-4 py-4"><span class="rounded-full {{ $requirement->status === 'aktif' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-700' }} px-2 py-1 text-xs font-semibold">{{ ucfirst($requirement->status) }}</span></td><td class="px-4 py-4 text-right"><a href="{{ route('management.document-requirements.edit', $requirement) }}" class="rounded-lg border border-teal-200 px-3 py-1.5 text-xs font-semibold text-teal-700">Edit</a><form class="inline" method="POST" action="{{ route('management.document-requirements.destroy', $requirement) }}" onsubmit="return confirm('Hapus persyaratan ini?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-200 px-3 py-1.5 text-xs font-semibold text-rose-700">Hapus</button></form></td></tr>@empty<tr><td colspan="7" class="px-4 py-10 text-center text-slate-500">Belum ada persyaratan dokumen.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-200 px-4 py-3">{{ $requirements->links() }}</div></div>
</div>
@endsection
