@extends('layouts.app')
@section('title', 'Pendaftaran KP - '.config('app.name'))
@section('page_title', 'Pendaftaran KP')
@section('content')
<div class="space-y-5">
@if(! auth()->user()->profile_completed)<div class="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">Lengkapi profil terlebih dahulu sebelum mendaftar KP.</div>@endif
<section class="grid gap-4 md:grid-cols-5">@foreach(['Profil','Pendaftaran','Upload Berkas','Verifikasi','Siap Pilih Tempat'] as $step)<div class="rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p class="text-xs font-semibold uppercase tracking-wide text-teal-700">Step {{ $loop->iteration }}</p><p class="mt-2 text-sm font-bold text-slate-950">{{ $step }}</p></div>@endforeach</section>
<section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div class="flex items-center justify-between"><div><h2 class="text-lg font-bold text-slate-950">Periode Dibuka</h2><p class="text-sm text-slate-500">Pilih periode yang sedang membuka pendaftaran.</p></div><a href="{{ route('student.kp-registrations.create') }}" class="rounded-lg bg-teal-600 px-4 py-2 text-sm font-semibold text-white">Daftar KP</a></div><div class="mt-4 grid gap-3 md:grid-cols-2">@forelse($openPeriods as $period)<div class="rounded-xl border border-slate-200 p-4"><h3 class="font-bold">{{ $period->name }}</h3><p class="mt-1 text-sm text-slate-500">{{ $period->registration_start_at?->format('d M Y H:i') }} - {{ $period->registration_end_at?->format('d M Y H:i') }}</p></div>@empty<p class="rounded-lg bg-slate-50 px-4 py-3 text-sm text-slate-500 md:col-span-2">Belum ada periode KP yang dibuka.</p>@endforelse</div></section>
<section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 class="text-lg font-bold text-slate-950">Pendaftaran Saya</h2><div class="mt-4 space-y-3">@forelse($registrations as $registration)<div class="rounded-xl border border-slate-200 p-4"><div class="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><h3 class="font-bold">{{ $registration->period->name }}</h3><p class="text-sm text-slate-500">{{ $registration->registration_number ?: 'Belum submit' }} - Progress berkas {{ $registration->progressPercentage() }}%</p></div><div class="flex items-center gap-2"><span class="rounded-full {{ $registration->statusBadgeClass() }} px-3 py-1 text-xs font-semibold">{{ $registration->statusLabel() }}</span><a href="{{ route('student.kp-registrations.show', $registration) }}" class="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-700">Detail</a></div></div></div>@empty<p class="rounded-lg bg-slate-50 px-4 py-3 text-sm text-slate-500">Belum ada pendaftaran KP.</p>@endforelse</div></section>
</div>
@endsection
