@extends('layouts.app')
@section('title', 'Detail Pendaftaran KP - '.config('app.name'))
@section('page_title', 'Detail Pendaftaran KP')
@section('content')
<div class="space-y-5">@if($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 class="text-xl font-bold">{{ $registration->period->name }}</h2><p class="text-sm text-slate-500">{{ $registration->registration_number ?: 'Nomor dibuat saat submit' }}</p></div><span class="rounded-full {{ $registration->statusBadgeClass() }} px-3 py-1 text-xs font-semibold">{{ $registration->statusLabel() }}</span></div><div class="mt-5 h-3 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-teal-600" style="width: {{ $registration->progressPercentage() }}%"></div></div><p class="mt-2 text-sm text-slate-500">Progress berkas {{ $registration->progressPercentage() }}%</p>@if($registration->isEligibleForPlaceSelection())<div class="mt-4 rounded-lg bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">Terverifikasi - Siap mengikuti pemilihan tempat KP.</div>@endif</section>
<section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h3 class="text-lg font-bold">Berkas Persyaratan</h3><div class="mt-4 space-y-3">@foreach($registration->period->documentRequirements->where('status','aktif') as $requirement)@php($document = $registration->documents->firstWhere('kp_document_requirement_id', $requirement->id))<div class="rounded-xl border border-slate-200 p-4"><div class="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><h4 class="font-bold">{{ $requirement->name }} @if($requirement->is_required)<span class="text-rose-600">*</span>@endif</h4><p class="text-sm text-slate-500">{{ $requirement->description ?: 'Upload file '.$requirement->allowed_file_types.', maksimal '.$requirement->max_file_size_mb.'MB.' }}</p>@if($document?->review_note)<p class="mt-2 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-800">{{ $document->review_note }}</p>@endif</div><span class="rounded-full {{ $document?->statusBadgeClass() ?? 'bg-slate-100 text-slate-700' }} px-3 py-1 text-xs font-semibold">{{ $document?->statusLabel() ?? 'Belum Upload' }}</span></div>@if($document?->file_path)<a href="{{ route('student.kp-registrations.documents.download', [$registration, $document]) }}" class="mt-3 inline-block text-sm font-semibold text-teal-700">Download {{ $document->original_filename }}</a>@endif@if(in_array($document?->status, [null,'belum_upload','revisi','ditolak','menunggu'], true) && ! $registration->isVerified())<form method="POST" action="{{ route('student.kp-registrations.documents.store', [$registration, $requirement]) }}" enctype="multipart/form-data" class="mt-3 flex flex-col gap-2 md:flex-row">@csrf<input type="file" name="document" class="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Upload</button></form>@endif</div>@endforeach</div></section>
<div class="flex justify-end gap-2">@if(! $registration->isVerified())<form method="POST" action="{{ route('student.kp-registrations.submit', $registration) }}" onsubmit="return confirm('Submit pendaftaran untuk diverifikasi?')">@csrf<button class="rounded-lg bg-teal-600 px-4 py-2 text-sm font-semibold text-white">Submit Pendaftaran</button></form><form method="POST" action="{{ route('student.kp-registrations.cancel', $registration) }}" onsubmit="return confirm('Batalkan pendaftaran?')">@csrf<button class="rounded-lg border border-rose-200 px-4 py-2 text-sm font-semibold text-rose-700">Batalkan</button></form>@endif</div>
</div>
@endsection
