@extends('layouts.app')
@section('title','Review Laporan - '.config('app.name'))
@section('page_title','Review Laporan')
@section('content')
<div class="space-y-5">
<section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><form method="GET" class="grid gap-3 md:grid-cols-[1fr_220px_auto]"><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Cari nama/NIM" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><select name="status" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua Status</option>@foreach(['draft'=>'Draft','menunggu_review'=>'Menunggu Review','revisi'=>'Revisi','disetujui'=>'Disetujui','ditolak'=>'Ditolak'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filter</button></form></section>
<section class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table><thead><tr><th>Mahasiswa</th><th>Tempat</th><th>Versi</th><th>Status</th><th>Submit</th><th class="text-right">Aksi</th></tr></thead><tbody>@forelse($reports as $report)<tr><td><div class="font-semibold">{{ $report->assignment->student->user->name }}</div><div class="text-xs text-slate-500">{{ $report->assignment->student->nim ?: '-' }}</div></td><td>{{ $report->assignment->place->name }}</td><td>{{ $report->current_version }}</td><td><span class="rounded-full px-2 py-1 text-xs font-semibold ring-1 {{ $report->statusBadgeClass() }}">{{ $report->statusLabel() }}</span></td><td>{{ $report->submitted_at?->format('d M Y H:i') ?? '-' }}</td><td class="text-right"><a href="{{ route('internal-supervisor.final-reports.show',$report) }}" class="rounded-lg border border-teal-200 px-3 py-1.5 text-xs font-semibold text-teal-700">Detail</a></td></tr>@empty<tr><td colspan="6" class="py-10 text-center text-slate-500">Belum ada laporan mahasiswa bimbingan.</td></tr>@endforelse</tbody></table></div><div class="border-t px-4 py-3">{{ $reports->links() }}</div></section>
</div>
@endsection
