@extends('layouts.app')
@section('title','Jadwal Sidang - '.config('app.name'))
@section('page_title','Jadwal Sidang')
@section('content')
<div class="space-y-5">
<x-ui.card><form method="GET" class="grid gap-3 md:grid-cols-[220px_220px_auto]"><select name="period" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua Periode</option>@foreach($periods as $period)<option value="{{ $period->id }}" @selected(($filters['period'] ?? '') == $period->id)>{{ $period->name }}</option>@endforeach</select><select name="status" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua Status</option>@foreach(['dijadwalkan'=>'Dijadwalkan','selesai'=>'Selesai','ditunda'=>'Ditunda','dibatalkan'=>'Dibatalkan'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filter</button></form></x-ui.card>
<section class="si-table-wrap"><div class="overflow-x-auto"><table><thead><tr><th>Mahasiswa</th><th>Pembimbing</th><th>Penguji</th><th>Jadwal</th><th>Mode</th><th>Status</th><th class="text-right">Aksi</th></tr></thead><tbody>@forelse($exams as $exam)<tr><td><div class="font-semibold">{{ $exam->assignment->student->user->name }}</div><div class="text-xs text-slate-500">{{ $exam->assignment->student->nim ?: '-' }}</div></td><td>{{ $exam->supervisor ? lecturer_display_name($exam->supervisor) : '-' }}</td><td>{{ $exam->examiner ? lecturer_display_name($exam->examiner) : '-' }}</td><td>{{ $exam->scheduleLabel() }}</td><td>{{ $exam->modeLabel() }}</td><td><span class="rounded-full px-2 py-1 text-xs font-semibold ring-1 {{ $exam->statusBadgeClass() }}">{{ $exam->statusLabel() }}</span></td><td class="text-right"><a href="{{ route('management.exams.show',$exam) }}" class="rounded-lg border border-cyan-200 px-3 py-1.5 text-xs font-semibold text-cyan-700">Detail</a></td></tr>@empty<tr><td colspan="7" class="py-10 text-center text-slate-500">Belum ada jadwal sidang.</td></tr>@endforelse</tbody></table></div><div class="border-t px-4 py-3">{{ $exams->links() }}</div></section>
</div>
@endsection
