@extends('layouts.app')
@section('title','Monitoring Logbook - '.config('app.name'))
@section('page_title','Monitoring Logbook')
@section('content')
<div class="space-y-5">
<section class="grid gap-3 md:grid-cols-6">@foreach(['total'=>'Total','draft'=>'Draft','pending'=>'Menunggu','approved'=>'Disetujui','revision'=>'Revisi','rejected'=>'Ditolak'] as $key=>$label)<div class="rounded-xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p class="text-xs font-semibold uppercase text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold text-slate-950">{{ $stats[$key] ?? 0 }}</p></div>@endforeach</section>
<section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><form method="GET" class="grid gap-3 md:grid-cols-[1fr_220px_220px_auto]"><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Cari mahasiswa/tempat/judul" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><select name="period" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua Periode</option>@foreach($periods as $period)<option value="{{ $period->id }}" @selected(($filters['period'] ?? '') == $period->id)>{{ $period->name }}</option>@endforeach</select><select name="status" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua Status</option>@foreach(['draft'=>'Draft','menunggu_validasi'=>'Menunggu Validasi','disetujui'=>'Disetujui','revisi'=>'Revisi','ditolak'=>'Ditolak'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filter</button></form></section>
<section class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-500"><tr><th class="px-4 py-3">Mahasiswa</th><th class="px-4 py-3">Tanggal</th><th class="px-4 py-3">Judul</th><th class="px-4 py-3">Tempat</th><th class="px-4 py-3">Pembimbing</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($logbooks as $logbook)<tr><td class="px-4 py-4"><div class="font-semibold">{{ $logbook->assignment->student->user->name }}</div><div class="text-xs text-slate-500">{{ $logbook->assignment->student->nim ?: '-' }}</div></td><td class="px-4 py-4">{{ $logbook->activity_date->format('d M Y') }}</td><td class="px-4 py-4 font-semibold text-slate-900">{{ $logbook->activity_title }}</td><td class="px-4 py-4">{{ $logbook->assignment->place->name }}</td><td class="px-4 py-4"><div>{{ $logbook->assignment->internalSupervisor ? lecturer_display_name($logbook->assignment->internalSupervisor) : '-' }}</div><div class="text-xs text-slate-500">{{ $logbook->assignment->fieldSupervisor?->user?->name ?? '-' }}</div></td><td class="px-4 py-4"><span class="rounded-full px-2 py-1 text-xs font-semibold ring-1 {{ $logbook->statusBadgeClass() }}">{{ $logbook->statusLabel() }}</span></td><td class="px-4 py-4 text-right"><a href="{{ route('management.logbooks.show',$logbook) }}" class="rounded-lg border border-teal-200 px-3 py-1.5 text-xs font-semibold text-teal-700">Detail</a></td></tr>@empty<tr><td colspan="7" class="px-4 py-10 text-center text-slate-500">Belum ada logbook.</td></tr>@endforelse</tbody></table></div><div class="border-t px-4 py-3">{{ $logbooks->links() }}</div></section>
</div>
@endsection
