@csrf
@if($period->exists) @method('PUT') @endif
<section class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
    <div class="grid gap-4 md:grid-cols-2">
        <div><label class="text-sm font-semibold text-slate-700">Nama Periode</label><input name="name" value="{{ old('name', $period->name) }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error('name')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm font-semibold text-slate-700">Tahun Akademik</label><input name="academic_year" value="{{ old('academic_year', $period->academic_year) }}" placeholder="2025/2026" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"></div>
        <div><label class="text-sm font-semibold text-slate-700">Semester</label><select name="semester" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Belum ditentukan</option>@foreach(['ganjil','genap','antara'] as $semester)<option value="{{ $semester }}" @selected(old('semester', $period->semester) === $semester)>{{ ucfirst($semester) }}</option>@endforeach</select></div>
        <div><label class="text-sm font-semibold text-slate-700">Status</label><select name="status" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@foreach(\App\Models\KpPeriod::STATUSES as $status)<option value="{{ $status }}" @selected(old('status', $period->status ?: 'draft') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div>
        @foreach(['registration_start_at' => 'Mulai Pendaftaran', 'registration_end_at' => 'Akhir Pendaftaran', 'document_verification_start_at' => 'Mulai Verifikasi Dokumen', 'document_verification_end_at' => 'Akhir Verifikasi Dokumen', 'selection_start_at' => 'Mulai Pemilihan Tempat', 'selection_end_at' => 'Akhir Pemilihan Tempat'] as $field => $label)
            <div><label class="text-sm font-semibold text-slate-700">{{ $label }} <span class="font-normal text-slate-500">(WIB)</span></label><input type="datetime-local" name="{{ $field }}" value="{{ old($field, $period->{$field}?->format('Y-m-d\TH:i')) }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error($field)<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
        @endforeach
        <div><label class="text-sm font-semibold text-slate-700">Tanggal Mulai KP</label><input type="date" name="kp_start_date" value="{{ old('kp_start_date', $period->kp_start_date?->format('Y-m-d')) }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"></div>
        <div><label class="text-sm font-semibold text-slate-700">Tanggal Akhir KP</label><input type="date" name="kp_end_date" value="{{ old('kp_end_date', $period->kp_end_date?->format('Y-m-d')) }}" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">@error('kp_end_date')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
        <div class="md:col-span-2"><label class="text-sm font-semibold text-slate-700">Deskripsi</label><textarea name="description" rows="4" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm">{{ old('description', $period->description) }}</textarea><p class="mt-2 text-xs text-slate-500">Jadwal pemilihan tempat akan digunakan untuk membuka fitur pemilihan tempat KP pada tahap berikutnya.</p></div>
    </div>
    <div class="mt-6 flex justify-end gap-2"><a href="{{ route('management.kp-periods.index') }}" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Batal</a><button class="rounded-lg bg-teal-600 px-4 py-2 text-sm font-semibold text-white">Simpan Periode</button></div>
</section>
