@extends('layouts.app')
@section('title','Validasi Logbook - '.config('app.name'))
@section('page_title','Validasi Logbook')
@section('content')
<div class="space-y-5">
<section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><form method="GET" class="grid gap-3 md:grid-cols-[1fr_220px_auto]"><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Cari nama/NIM" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><select name="status" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua Status</option>@foreach(['draft'=>'Draft','menunggu_validasi'=>'Menunggu Validasi','disetujui'=>'Disetujui','revisi'=>'Revisi','ditolak'=>'Ditolak'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Filter</button></form></section>
<section class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-500"><tr><th class="px-4 py-3">Mahasiswa</th><th class="px-4 py-3">Tanggal</th><th class="px-4 py-3">Judul</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($logbooks as $logbook)<tr><td class="px-4 py-4"><div class="font-semibold">{{ $logbook->assignment->student->user->name }}</div><div class="text-xs text-slate-500">{{ $logbook->assignment->student->nim ?: '-' }}</div></td><td class="px-4 py-4">{{ $logbook->activity_date->format('d M Y') }}</td><td class="px-4 py-4">{{ $logbook->activity_title }}</td><td class="px-4 py-4"><span class="rounded-full px-2 py-1 text-xs font-semibold ring-1 {{ $logbook->statusBadgeClass() }}">{{ $logbook->statusLabel() }}</span></td><td class="px-4 py-4 text-right"><a href="{{ route('field-supervisor.logbooks.show',$logbook) }}" class="rounded-lg border border-teal-200 px-3 py-1.5 text-xs font-semibold text-teal-700">Detail</a></td></tr>@empty<tr><td colspan="5" class="px-4 py-10 text-center text-slate-500">Belum ada logbook mahasiswa KP.</td></tr>@endforelse</tbody></table></div><div class="border-t px-4 py-3">{{ $logbooks->links() }}</div></section>
</div>
@endsection
